version: '2.0'
services:

  # PHP Service
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
          WWWGUID: '${WWWGUID:-1000}'
    image: laravel-5.7/php-7.4
    container_name: app
    restart: unless-stopped
    tty: true
    user: 1000:1000
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      WWWUSER: '${WWWUSER:-1000}'
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
      - ./docker/php.ini:/usr/local/etc/php/conf.d/laravel.ini
    networks:
      - app-network
    depends_on:
      - db

  # Composer files after app creation
  # composer:
  #   container_name: composer_installation
  #   image: composer
  #   volumes:
  #     - ./:/var/www/html/
  #   command: composer install --ignore-platform-reqs
  #   depends_on:
  #     - app

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx.conf:/etc/nginx/conf.d/app.conf
    networks:
      - app-network
    depends_on:
      - app

  # Postgres
  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
      POSTGRES_DB: testedevweb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - dbdata:/var/lib/postgresql/data/
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local
